server:
  assets-path: /app/assets

theme:
  # Note: assets are cached by the browser, changes to the CSS file
  # will not be reflected until the browser cache is cleared (Ctrl+F5)
  custom-css-file: /assets/user.css

include: !include glance/config/home.yml

pages:
  - name: Home
    columns:
      - size: small
        widgets:
          - type: videos
            channels:
              - UCH8688NYs4zdEALBE6-LUhQ
      - size: full
        widgets:
          - type: group
            widgets:
              - type: search
                title: Search
                search-engine: google
                search-url: https://www.google.com/search?q={searchTerms}
                show-search-button: true
                show-search-box: true
          - type: group
            widgets:
              - type: reddit
                subreddit: ActualPublicFreakouts
                show-thumbnails: true
              - type: reddit
                subreddit: PublicFreakout
                show-thumbnails: true
              - type: reddit
                subreddit: Whatcouldgowrong
                show-thumbnails: true
              - type: reddit
                subreddit: ImTheMainCharacter
                show-thumbnails: true
              
          - type: group
            widgets:
              - type: rss
                title: RSS Feed
                feeds: 
                  - name: Reddit
                    url: https://www.reddit.com/r/PublicFreakout/.rss
                  - name: Reddit
                    url: https://www.reddit.com/r/ActualPublicFreakouts/.rss
                  - name: Reddit
                    url: https://www.reddit.com/r/Whatcouldgowrong/.rss
                  - name: Reddit
                    url: https://www.reddit.com/r/ImTheMainCharacter/.rss