server:
  assets-path: /app/assets

theme:
  # Note: assets are cached by the browser, changes to the CSS file
  # will not be reflected until the browser cache is cleared (Ctrl+F5)
  custom-css-file: /assets/user.css

include: !include glance/config/home.yml

pages:
  - name: Home 
    columns:
      - size: small
        widgets:
          - type: videos
            channels:
              - UCH8688NYs4zdEALBE6-LUhQ
              - UCUwBr3DpMT3WhaGuHnJcakQ
              - UCYAu4BumzvauT_zA_rMa0Qw
              - UCe1IA5kmY578O_Qo7Skr-TQ
              - UC7s1onGtoO5YHFPHRK63CIg
              - UCD5_NZk4-TamMYBcN12kcWA
              - UCIFtt3TNWmgmXwsZRRmx_hQ
              - UCKwQIZHN3gwC37xdVPO-h6Q
            style: 'vertical-list'
            options:
              show-title: true
              show-thumbnails: true
            limit: 100  # Increase or decrease as needed
      - size: full
        widgets:
          - type: group
            widgets:
              - type: search
                title: Google Search
                search-engine: google
                search-url: https://www.google.com/search?q={searchTerms}
                show-search-button: true
                show-search-box: true
                
          - type: group
            widgets:
              - type: reddit
                title: FullStack
                subreddit: FullStack
                show-subreddit: true
                show-subreddit-title: true
                show-subreddit-description: true
                show-thumbnails: false
              - type: reddit
                title: ChatGPT
                subreddit: ChatGPT
                show-subreddit: true
                show-subreddit-title: true
                show-subreddit-description: true
                show-thumbnails: false
              - type: reddit
                title: FullStackDevelopers
                subreddit: FullStackDevelopers
                show-subreddit: true
                show-subreddit-title: true
                show-subreddit-description: true
                show-thumbnails: false
              - type: reddit
                title: Business ideas
                subreddit: businessideas
                show-subreddit: true
                show-subreddit-title: true
                show-subreddit-description: true
                show-thumbnails: false
              - type: reddit  
                title: Startups
                subreddit: startups
                show-subreddit: true
                show-subreddit-title: true
                show-subreddit-description: true
                show-thumbnails: false
              - type: reddit
                title: Business
                subreddit: business
                show-subreddit: true
                show-subreddit-title: true
                show-subreddit-description: true
                show-thumbnails: false
              - type: reddit
                title: Technology
                subreddit: technology
                show-subreddit: true
                show-subreddit-title: true
                show-subreddit-description: true
                show-thumbnails: false
              - type: reddit
                title: Programming
                subreddit: programming
                show-subreddit: true
                show-subreddit-title: true
                show-subreddit-description: true
                show-thumbnails: false
              - type: reddit
                title: career guidance
                subreddit: career_guidance
                show-subreddit: true
                show-subreddit-title: true
                show-subreddit-description: true
                show-thumbnails: false
              - type: reddit
                title: JavaScript
                subreddit: javascript
                show-subreddit: true
                show-subreddit-title: true
                show-subreddit-description: true
                show-thumbnails: false
        
          - type: group
            widgets:
              - type: rss
                title: RSS Feed
                feeds: 
                  # Removed Reddit RSS feeds to avoid 429 errors
                  # Example: Add a non-Reddit RSS feed instead
                  - title: NYT Home
                    url: https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml
                  - title: BBC News
                    url: http://feeds.bbci.co.uk/news/rss.xml
                  - title: Fox News
                    url: http://feeds.foxnews.com/foxnews/latest
                  - title: Politico
                    url: https://www.politico.com/rss/politicopicks.xml
                  - title: Yahoo News
                    url: https://news.yahoo.com/rss/
                        
          - type: group
            widgets:
              - type: rss
                title: Business Feed
                feeds:
                  - title: Investopedia
                    url: https://www.investopedia.com/feedbuilder/feed/getfeed/?name=investopedia&feed=investopedia
                  - title: Business Insider
                    url: https://www.businessinsider.com/rss
                  - title: Fortune
                    url: https://fortune.com/feed/
                  - title: Bloomberg
                    url: https://www.bloomberg.com/feed/podcast/etf-report.xml
                  - title: Forbes
                    url: https://www.forbes.com/real-time/feed2/topic/business/

          - type: group
            widgets:
              - type: markets
                title: Markets
                show-title: true
                show-description: true
                show-thumbnails: true
                markets:
                  - name: S&P 500
                    symbol: ^GSPC
                  - name: NASDAQ
                    symbol: ^IXIC
                  - name: Dow Jones
                    symbol: ^DJI
                  - name: Bitcoin
                    symbol: BTC-USD
                  - name: Ethereum
                    symbol: ETH-USD
                  - name: Gold
                    symbol: GC=F
                  - name: Apple
                    symbol: AAPL
                  - name: Microsoft
                    symbol: MSFT
                  - name: Amazon
                    symbol: AMZN
                  - name: Google
                    symbol: GOOGL
                  - name: Tesla
                    symbol: TSLA
                  - name: Meta
                    symbol: META
                  - name: Netflix
                    symbol: NFLX
                  - name: Nvidia
                    symbol: NVDA
                  - name: AMD
                    symbol: AMD
                  - name: Intel
                    symbol: INTC

          - type: group
            widgets:
              - type: repository
                title: Repositories
                repository: 'sjmiguel8/devops'
              - type: repository
                title: Repositories Pg 2
                repository: 'sjmiguel8/SSDA'
                
                    

  - name: Reddit
    columns:
      - size: full
        widgets:
          - type: reddit
            title: FullStack
            subreddit: FullStack
            show-subreddit: true
            show-subreddit-title: true
            show-subreddit-description: true
            show-thumbnails: true
          - type: reddit
            title: ChatGPT
            subreddit: ChatGPT
            show-subreddit: true
            show-subreddit-title: true
            show-subreddit-description: true
            show-thumbnails: true
          - type: reddit
            title: FullStackDevelopers
            subreddit: FullStackDevelopers
            show-subreddit: true
            show-subreddit-title: true
            show-subreddit-description: true
            show-thumbnails: true
          - type: reddit
            title: Business ideas
            subreddit: businessideas
            show-subreddit: true
            show-subreddit-title: true
            show-subreddit-description: true
            show-thumbnails: true
          - type: reddit
            title: Startups
            subreddit: startups
            show-subreddit: true
            show-subreddit-title: true
            show-subreddit-description: true
            show-thumbnails: true
          - type: reddit  
            title: Business
            subreddit: business
            show-subreddit: true
            show-subreddit-title: true
            show-subreddit-description: true
            show-thumbnails: true

          - type: reddit
            title: Technology
            subreddit: technology
            show-subreddit: true
            show-subreddit-title: true
            show-subreddit-description: true
            show-thumbnails: true
          - type: reddit
            title: Programming
            subreddit: programming
            show-subreddit: true
            show-subreddit-title: true
            show-subreddit-description: true
            show-thumbnails: true
          - type: reddit
            title: career guidance
            subreddit: career_guidance
            show-subreddit: true
            show-subreddit-title: true
            show-subreddit-description: true
            show-thumbnails: true
          - type: reddit
            title: JavaScript
            subreddit: javascript
            show-subreddit: true
            show-subreddit-title: true
            show-subreddit-description: true
            show-thumbnails: true

  - name: RSS
    columns:
      - size: full
        widgets:
          - type: rss
            title: News Feed
            feeds: 
              - title: NYT Home
                url: https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml
              - title: BBC News
                url: http://feeds.bbci.co.uk/news/rss.xml
              - title: Fox News
                url: http://feeds.foxnews.com/foxnews/latest
              - title: Politico
                url: https://www.politico.com/rss/politicopicks.xml
              - title: Yahoo News
                url: https://news.yahoo.com/rss/
          - type: rss
            title: Business Feed
            feeds:
                  - title: Investopedia
                    url: https://www.investopedia.com/feedbuilder/feed/getfeed/?name=investopedia&feed=investopedia
                  - title: Business Insider
                    url: https://www.businessinsider.com/rss
                  - title: Fortune
                    url: https://fortune.com/feed/
                  - title: Bloomberg
                    url: https://www.bloomberg.com/feed/podcast/etf-report.xml
                  - title: Forbes
                    url: https://www.forbes.com/real-time/feed2/topic/business/
          - type: rss
            title: Technology Feed
            feeds:
              - title: TechCrunch
                url: https://techcrunch.com/feed/
              - title: Wired
                url: https://www.wired.com/feed/
              - title: The Verge
                url: https://www.theverge.com/rss/index.xml
              - title: Ars Technica
                url: https://arstechnica.com/feed/
              - title: Engadget
                url: https://www.engadget.com/rss.xml
          - type: rss
            title: Programming Feed
            feeds:
              - title: Hacker News
                url: https://news.ycombinator.com/rss
              - title: Dev.to
                url: https://dev.to/feed
              - title: Stack Overflow
                url: https://stackoverflow.com/feeds/tag?tagnames=javascript&sort=newest
              - title: GitHub
                url: https://github.blog/feed/
              - title: CodeProject
                url: https://www.codeproject.com/webservices/webservice.ashx?rss=true

               
            columns:
              - size: full
                widgets:
                  - type: group
                    widgets:
                      - type: search
                        title: Google Search
                        search-engine: google
                        search-url: https://www.google.com/search?q={searchTerms}
                        show-search-button: true
                        show-search-box: true

  - name: Markets
    columns:
      - size: full
        widgets:
          - type: markets
            style: 'grid-cards'
            title: Markets
            markets:
              - name: S&P 500
                symbol: ^GSPC
              - name: NASDAQ
                symbol: ^IXIC
              - name: Dow Jones
                symbol: ^DJI
              - name: Bitcoin
                symbol: BTC-USD
              - name: Ethereum
                symbol: ETH-USD
              - name: Gold
                symbol: GC=F
              - name: Apple
                symbol: AAPL
              - name: Microsoft
                symbol: MSFT
              - name: Amazon
                symbol: AMZN
              - name: Google
                symbol: GOOGL
              - name: Tesla
                symbol: TSLA
              - name: Meta
                symbol: META
              - name: Netflix
                symbol: NFLX
      - size: small
        widgets:
          - type: news
            title: News
            show-title: true
            show-description: true
            show-thumbnails: true
            sources:
              - name: Investopedia
                url: https://www.investopedia.com/
              - name: Yahoo Finance
                url: https://finance.yahoo.com/
              - name: CNBC
                url: https://www.cnbc.com/
              - name: Bloomberg
                url: https://www.bloomberg.com/
              - name: Reuters
                url: https://www.reuters.com/
              - name: MarketWatch
                url: https://www.marketwatch.com/

  - name: Videos
    columns:
        - size: full
          widgets:
            - type: videos
              channels:
                - UCH8688NYs4zdEALBE6-LUhQ
                - UCUwBr3DpMT3WhaGuHnJcakQ
                - UCYAu4BumzvauT_zA_rMa0Qw
                - UCe1IA5kmY578O_Qo7Skr-TQ
                - UC7s1onGtoO5YHFPHRK63CIg
                - UCD5_NZk4-TamMYBcN12kcWA
                - UCIFtt3TNWmgmXwsZRRmx_hQ
                - UCKwQIZHN3gwC37xdVPO-h6Q
              style: 'grid-cards'
              options:
                show-title: true
                show-thumbnails: true
              limit: 100 
        - size: small
          widgets:
            - type: group
              widgets:
                - type: search
                  title: Youtube Search
                  search-engine: youtube
                  search-url: https://www.youtube.com/results?search_query={searchTerms}
                  show-search-button: true
                  show-search-box: true
