server:
  assets-path: /app/assets

theme:
  # Note: assets are cached by the browser, changes to the CSS file
  # will not be reflected until the browser cache is cleared (Ctrl+F5)
  custom-css-file: /assets/user.css

include: !include glance/config/home.yml

pages:
  - name: Home
    columns:
      - size: small
        widgets:
          - type: videos
            channels:
              - UCH8688NYs4zdEALBE6-LUhQ
              - UCUwBr3DpMT3WhaGuHnJcakQ
              - UCYAu4BumzvauT_zA_rMa0Qw
              - UCe1IA5kmY578O_Qo7Skr-TQ
              - UC7s1onGtoO5YHFPHRK63CIg
              - UCD5_NZk4-TamMYBcN12kcWA
              - UCIFtt3TNWmgmXwsZRRmx_hQ
              - UCKwQIZHN3gwC37xdVPO-h6Q
            style: 'grid-cards'
            options:
              show-title: true
              show-description: true
              show-thumbnails: true
            limit: 100  # Increase or decrease as needed
      - size: full
        widgets:
          - type: group
            widgets:
              - type: search
                title: Google Search
                search-engine: google
                search-url: https://www.google.com/search?q={searchTerms}
                show-search-button: true
                show-search-box: true
                
          - type: group
            widgets:
              - type: reddit
                title: FullStack
                subreddit: FullStack
                show-subreddit: true
                show-subreddit-title: true
                show-subreddit-description: true
                show-thumbnails: true
              - type: reddit
                title: ChatGPT
                subreddit: ChatGPT
                show-subreddit: true
                show-subreddit-title: true
                show-subreddit-description: true
                show-thumbnails: true
              - type: reddit
                title: FullStackDevelopers
                subreddit: FullStackDevelopers
                show-subreddit: true
                show-subreddit-title: true
                show-subreddit-description: true
                show-thumbnails: true
              - type: reddit
                title: Business ideas
                subreddit: businessideas
                show-subreddit: true
                show-subreddit-title: true
                show-subreddit-description: true
                show-thumbnails: true
              - type: reddit  
                title: Startups
                subreddit: startups
                show-subreddit: true
                show-subreddit-title: true
                show-subreddit-description: true
                show-thumbnails: true
              - type: reddit
                title: Business
                subreddit: business
                show-subreddit: true
                show-subreddit-title: true
                show-subreddit-description: true
                show-thumbnails: true
              - type: reddit
                title: Technology
                subreddit: technology
                show-subreddit: true
                show-subreddit-title: true
                show-subreddit-description: true
                show-thumbnails: true
              - type: reddit
                title: Programming
                subreddit: programming
                show-subreddit: true
                show-subreddit-title: true
                show-subreddit-description: true
                show-thumbnails: true
              - type: reddit
                title: career guidance
                subreddit: career_guidance
                show-subreddit: true
                show-subreddit-title: true
                show-subreddit-description: true
                show-thumbnails: true
              - type: reddit
                title: JavaScript
                subreddit: javascript
                show-subreddit: true
                show-subreddit-title: true
                show-subreddit-description: true
                show-thumbnails: true
        
          - type: group
            widgets:
              - type: rss
                title: RSS Feed
                feeds: 
                  # Removed Reddit RSS feeds to avoid 429 errors
                  # Example: Add a non-Reddit RSS feed instead
                  - title: NYT Home
                    url: https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml
                  - title: BBC News
                    url: http://feeds.bbci.co.uk/news/rss.xml
                  - title: Fox News
                    url: http://feeds.foxnews.com/foxnews/latest
                  - title: Politico
                    url: https://www.politico.com/rss/politicopicks.xml
                  - title: Yahoo News
                    url: https://news.yahoo.com/rss/
                        
          - type: group
            widgets:
              - type: markets
                title: Markets
                show-title: true
                show-description: true
                show-thumbnails: true
                markets:
                  - name: S&P 500
                    symbol: ^GSPC
                  - name: NASDAQ
                    symbol: ^IXIC
                  - name: Dow Jones
                    symbol: ^DJI
                  - name: Bitcoin
                    symbol: BTC-USD
                  - name: Ethereum
                    symbol: ETH-USD
                  - name: Gold
                    symbol: GC=F
                  - name: Apple
                    symbol: AAPL
                  - name: Microsoft
                    symbol: MSFT

