server:
  assets-path: /app/assets

theme:
  # Note: assets are cached by the browser, changes to the CSS file
  # will not be reflected until the browser cache is cleared (Ctrl+F5)
  custom-css-file: /assets/user.css

include: !include glance/config/home.yml

pages:
  - name: Home
    columns:
      - size: small
        widgets:
          - type: videos
            channels:
              - UCH8688NYs4zdEALBE6-LUhQ
              - UCUwBr3DpMT3WhaGuHnJcakQ
              - UCYAu4BumzvauT_zA_rMa0Qw
              - UCe1IA5kmY578O_Qo7Skr-TQ
              - UC7s1onGtoO5YHFPHRK63CIg
              - UCD5_NZk4-TamMYBcN12kcWA
              - UCIFtt3TNWmgmXwsZRRmx_hQ
              - UCKwQIZHN3gwC37xdVPO-h6Q
            style: 'grid-cards'
            options:
              show-title: true
              show-description: true
              show-thumbnails: true
            limit: 100  # Increase or decrease as needed
      - size: full
        widgets:
          - type: group
            widgets:
              - type: search
                title: Search
                search-engine: google
                search-url: https://www.google.com/search?q={searchTerms}
                show-search-button: true
                show-search-box: true
                
          - type: group
            widgets:
              - type: reddit
                title: PublicFreakout
                subreddit: PublicFreakout
                show-subreddit: true
                show-subreddit-title: true
                show-subreddit-description: true
                show-thumbnails: true
              - type: reddit
                title: ActualPublicFreakouts
                subreddit: ActualPublicFreakouts
                show-subreddit: true
                show-subreddit-title: true
                show-subreddit-description: true
                show-thumbnails: true
              - type: reddit
                title: Whatcouldgowrong
                subreddit: Whatcouldgowrong
                show-subreddit: true
                show-subreddit-title: true
                show-subreddit-description: true
                show-thumbnails: true                
              - type: reddit
                title: ImTheMainCharacter
                subreddit: ImTheMainCharacter
                show-subreddit: true
                show-subreddit-title: true
                show-subreddit-description: true
                show-thumbnails: true
        
          - type: group
            widgets:
              - type: rss
                title: RSS Feed
                feeds: 
                  - name: PublicFreakout
                    url: https://reddit.com/r/PublicFreakout/.rss
                  - name: ActualPublicFreakouts
                    url: https://reddit.com/r/ActualPublicFreakouts/.rss
                  - name: Whatcouldgowrong
                    url: https://reddit.com/r/Whatcouldgowrong/.rss
                  - name: ImTheMainCharacter
                    url: https://reddit.com/r/ImTheMainCharacter/.rss

